name: Streamlit Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        echo "Installing requirements..."
        pip install -r requirements.txt
        echo "Installed packages:"
        pip list
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check required packages
      run: |
        python -c "import streamlit; print('Streamlit version:', streamlit.__version__)"
        python -c "import langchain; print('LangChain version:', langchain.__version__)"
        python -c "import langchain_community; print('LangChain Community version:', langchain_community.__version__)"
    - name: Run Streamlit app
      run: |
        streamlit run streamlit_app.py &
        sleep 10
        kill $!
